import type { AiProvider } from "./types";

interface MockAiOptions {
  forceFailure: boolean;
  latencyMs: number;
  tokenLimit: number;
  rateLimitEveryN: number;
}

function hashString(value: string): number {
  let hash = 0;
  for (let index = 0; index < value.length; index += 1) {
    hash = (hash * 31 + value.charCodeAt(index)) >>> 0;
  }
  return hash;
}

function pickFromPrompt(prompt: string, label: string): string {
  const match = new RegExp(`^${label}:\\s*(.+)$`, "mi").exec(prompt);
  return match?.[1]?.trim() ?? "";
}

function countDimensions(prompt: string): number {
  const section = prompt.match(/PRE-COMPUTED SCORES[\s\S]*?data_sources/i)?.[0] ?? "";
  return (section.match(/^\s*-\s+/gm) ?? []).length;
}

function buildMockReport(prompt: string): string {
  const area = pickFromPrompt(prompt, "AREA") || "Unknown area";
  const intent = pickFromPrompt(prompt, "INTENT") || "research";
  const dimensions = Math.max(4, countDimensions(prompt));
  const seed = hashString(`${area}:${intent}`);

  const subScores = Array.from({ length: dimensions }, (_, index) => {
    const score = 40 + ((seed + index * 17) % 60);
    return {
      label: `Dimension ${index + 1}`,
      score,
      weight: Math.round(100 / dimensions),
      summary: `Deterministic mock summary for ${area} (${intent}).`,
      reasoning: "Generated by the local mock AI provider.",
      confidence: 0.8,
      confidence_reason: "Mock provider confidence is fixed for repeatability.",
    };
  });

  return JSON.stringify({
    area,
    intent,
    areaiq_score: 65 + (seed % 20),
    sub_scores: subScores,
    summary: `Mock narrative for ${area} (${intent}).`,
    sections: [
      {
        title: "Overview",
        content: `Deterministic mock content for ${area}.`,
        data_points: [{ label: "Seed", value: String(seed) }],
      },
    ],
    recommendations: [
      "Use the mock provider for repeatable local testing.",
      "Switch to Anthropic for real narrative generation.",
    ],
    data_sources: ["mock-ai"],
    generated_at: new Date(0).toISOString(),
  });
}

export class MockAiProvider implements AiProvider {
  private readonly options: MockAiOptions;
  private callCount = 0;

  constructor(options?: Partial<MockAiOptions>) {
    this.options = {
      forceFailure: process.env.OGA_MOCK_AI_FORCE_FAILURE === "true" || false,
      latencyMs: Number(process.env.OGA_MOCK_AI_LATENCY_MS || 0),
      tokenLimit: Number(process.env.OGA_MOCK_AI_TOKEN_LIMIT || 4096),
      rateLimitEveryN: Number(process.env.OGA_MOCK_AI_RATE_LIMIT_EVERY_N || 0),
      ...options,
    };
  }

  async generateNarrative(prompt: string): Promise<string> {
    this.callCount += 1;

    if (this.options.forceFailure) {
      throw new Error("Mock AI forced failure");
    }

    if (this.options.rateLimitEveryN > 0 && this.callCount % this.options.rateLimitEveryN === 0) {
      throw new Error("Mock AI rate limit exceeded");
    }

    if (this.options.latencyMs > 0) {
      await new Promise((resolve) => setTimeout(resolve, this.options.latencyMs));
    }

    const response = buildMockReport(prompt);
    return response.slice(0, this.options.tokenLimit);
  }
}
