import { describe, it, expect, vi, beforeEach } from "vitest";

/* AR-596 (Plan 059.4): /admin used to declare only `bearerToken` (the
   session JWT apps/web mints), which a browser-based Scalar "Try it"
   session can never obtain. It now also accepts a real API key
   (bearerAuth) via the same OR-auth helper as /me, /keys, /stripe — still
   gated by isSuperuser() same as before. An auto-generated playground key
   (AR-595) is rejected before that check ever runs. */

vi.mock("@/modules/auth/session-token", () => ({ verifySessionToken: vi.fn() }));
vi.mock("@/modules/api-keys", () => ({ validateApiKey: vi.fn() }));
vi.mock("@/modules/usage", () => ({ isSuperuser: vi.fn() }));
vi.mock("@/modules/admin", () => ({
  getAnalytics: vi.fn().mockResolvedValue({ ok: true }),
  getTrafficAnalytics: vi.fn(),
  getAudienceStats: vi.fn(),
  getUsageStats: vi.fn(),
  getRevenueExtras: vi.fn(),
  getMcpAdoption: vi.fn(),
  getTrainingCorpusStats: vi.fn(),
}));

import { buildApp } from "@/app";
import { verifySessionToken } from "@/modules/auth/session-token";
import { validateApiKey } from "@/modules/api-keys";
import { isSuperuser } from "@/modules/usage";

const app = await buildApp();

const mockVerify = vi.mocked(verifySessionToken);
const mockValidateKey = vi.mocked(validateApiKey);
const mockIsSuperuser = vi.mocked(isSuperuser);

beforeEach(() => {
  vi.clearAllMocks();
});

function get(headers?: Record<string, string>) {
  return app.inject({ method: "GET", url: "/admin/analytics", headers });
}

describe("GET /admin/analytics — auth matrix (AR-596, Plan 059.4)", () => {
  it("401s with no Authorization header", async () => {
    const res = await get();
    expect(res.statusCode).toBe(401);
  });

  it("401s when neither the session nor the API key validate", async () => {
    mockVerify.mockResolvedValue(null);
    mockValidateKey.mockResolvedValue(null);
    const res = await get({ authorization: "Bearer garbage" });
    expect(res.statusCode).toBe(401);
  });

  it("403s a valid session that isn't superuser", async () => {
    mockVerify.mockResolvedValue({ userId: "user_1" } as never);
    mockIsSuperuser.mockResolvedValue(false);
    const res = await get({ authorization: "Bearer session.jwt" });
    expect(res.statusCode).toBe(403);
  });

  it("200s a valid session that is superuser", async () => {
    mockVerify.mockResolvedValue({ userId: "staff_1" } as never);
    mockIsSuperuser.mockResolvedValue(true);
    const res = await get({ authorization: "Bearer session.jwt" });
    expect(res.statusCode).toBe(200);
  });

  it("200s a real (non-auto-generated) API key belonging to a superuser", async () => {
    mockVerify.mockResolvedValue(null);
    mockValidateKey.mockResolvedValue({ userId: "staff_1", orgId: null, autoGenerated: false } as never);
    mockIsSuperuser.mockResolvedValue(true);
    const res = await get({ authorization: "Bearer oga_realkey" });
    expect(res.statusCode).toBe(200);
  });

  it("403s an auto-generated playground key even if its owner is a superuser", async () => {
    mockVerify.mockResolvedValue(null);
    mockValidateKey.mockResolvedValue({ userId: "staff_1", orgId: null, autoGenerated: true } as never);
    mockIsSuperuser.mockResolvedValue(true);
    const res = await get({ authorization: "Bearer oga_autogenerated" });
    expect(res.statusCode).toBe(403);
    expect(res.json().code).toBe("auto_generated_key_not_allowed");
    expect(mockIsSuperuser).not.toHaveBeenCalled(); // rejected before the route's own gate runs
  });
});
