import type { FastifyRequest, FastifyReply } from "fastify";
import { verifySessionToken } from "../modules/auth/session-token";
import { validateApiKey } from "../modules/api-keys";
import { clientIpOf } from "./http";

/** Session (browser-user) auth via the JWT bridge — the counterpart to
   authenticate() (programmatic api-key auth). Verifies the short-lived token
   apps/web's server mints from its NextAuth session and resolves the userId, or
   sends 401 and resolves null. Used by the session-only Stripe routes. */
export async function authenticateSession(request: FastifyRequest, reply: FastifyReply): Promise<string | null> {
  const header = request.headers.authorization;
  if (!header || !header.startsWith("Bearer ")) {
    reply.code(401).send({ error: "Unauthorized" });
    return null;
  }
  const session = await verifySessionToken(header.slice(7));
  if (!session) {
    reply.code(401).send({ error: "Unauthorized" });
    return null;
  }
  return session.userId;
}

/** AR-596 (Plan 059.4): self-service account/billing/key-management routes
   (/me, /keys, /admin, /stripe) need to keep working for apps/web's
   session-JWT calls (the actual product — most users have no API key at
   all) AND become callable from Scalar's "Try it" with the caller's own
   API key, which was never possible before this story (those routes only
   declared `bearerToken`, a JWT a browser session can't produce).

   Tries the session JWT first (the primary, expected path), then falls
   back to a real API key. An auto-generated playground key (AR-595) is
   explicitly rejected here — these routes can mutate account/billing/key
   state, so a throwaway key must not reach them; the caller is told to
   create a real one at /keys instead. */
export async function authenticateSessionOrApiKey(request: FastifyRequest, reply: FastifyReply): Promise<string | null> {
  const header = request.headers.authorization;
  if (!header || !header.startsWith("Bearer ")) {
    reply.code(401).send({ error: "Unauthorized" });
    return null;
  }

  const session = await verifySessionToken(header.slice(7));
  if (session) return session.userId;

  const result = await validateApiKey(header.slice(7), clientIpOf(request));
  if (!result) {
    reply.code(401).send({ error: "Unauthorized" });
    return null;
  }
  if ("blocked" in result) {
    reply.code(403).send({ error: "Request IP is not in the key's allowlist.", code: result.blocked });
    return null;
  }
  if (result.autoGenerated) {
    reply.code(403).send({
      error: "This action requires a real API key, not an auto-generated playground key. Create one at /keys.",
      code: "auto_generated_key_not_allowed",
    });
    return null;
  }
  return result.userId;
}
