services:
  postgres:
    ports:
      - "55432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data:z
      - ../apps/web/tests/db/bootstrap:/docker-entrypoint-initdb.d:ro,z

  neon-proxy:
    ports:
      - "55433:55433"

  api:
    ports:
      - "8080:8080"

  web:
    ports:
      - "3000:3000"

  showcase:
    ports:
      - "3001:3000"

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"

  stripe-mock:
    ports:
      - "12111:12111"

  pgadmin:
    ports:
      - "8888:80"
