-- ============================================================================
-- Reset playground IP rate limit — RUN THIS IN NEON CONSOLE SQL EDITOR ONLY
-- ============================================================================
-- SAFETY: This file is NOT meant to be piped directly into psql or any client.
--         Read the instructions below, then manually copy-paste into Neon.
--
-- 1. Open https://console.neon.tech → project → SQL Editor
-- 2. Preview rows (safe — SELECT only):     run the SELECT block below
-- 3. Reset rows (destructive — DELETEs):    uncomment the DELETE block, then run
--
-- To reset for YOUR IP, replace '203.0.113.42' with your actual IP.
-- To reset ALL playground IPs, replace with 'playground:ip:%' + LIKE operator.
-- ============================================================================

-- ── 1. Preview (safe) ─────────────────────────────────────────────────────
-- Count rows for a specific playground IP:
--   SELECT COUNT(*) AS rows_found FROM rate_limit_entries WHERE identifier = 'playground:ip:203.0.113.42';
--
-- Or see every playground IP currently rate-limited (sorted by most rows):
--   SELECT identifier, COUNT(*) AS rows FROM rate_limit_entries
--    WHERE identifier LIKE 'playground:ip:%'
--    GROUP BY identifier
--    ORDER BY rows DESC;

-- ── 2. Reset (destructive — UNCOMMENT to run) ─────────────────────────────
-- DELETE FROM rate_limit_entries WHERE identifier = 'playground:ip:203.0.113.42';
--
-- To reset ALL playground IPs at once (use with care):
-- DELETE FROM rate_limit_entries WHERE identifier LIKE 'playground:ip:%';
